services:
  genesis-web:
    image: ghcr.io/mark-me/genesis-app:v0.0.1
    container_name: genesis-web
    ports:
      - "5000:5000"
    volumes:
      - ./configs:/configs   # lokale configs beschikbaar in container
      - ./output:/output     # output logs toegankelijk
    environment:
      - TZ=Europe/Amsterdam
      - FLASK_ENV=production
